apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata: {name: perconaservermongodbs.psmdb.percona.com}
spec:
  additionalPrinterColumns:
  - {JSONPath: .status.state, name: Status, type: string}
  - {JSONPath: .metadata.creationTimestamp, name: Age, type: date}
  group: psmdb.percona.com
  names:
    kind: PerconaServerMongoDB
    listKind: PerconaServerMongoDBList
    plural: perconaservermongodbs
    shortNames: [psmdb]
    singular: perconaservermongodb
  scope: Namespaced
  subresources:
    status: {}
  version: v1-4-0
  versions:
  - {name: v1-4-0, served: true, storage: true}
  - {name: v1, served: true, storage: false}
  - {name: v1-1-0, served: true, storage: false}
  - {name: v1-2-0, served: true, storage: false}
  - {name: v1-3-0, served: true, storage: false}
  - {name: v1alpha1, served: true, storage: false}

