apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app.kubernetes.io/name: postgres-operator
  name: postgresqls.acid.zalan.do
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.teamId
    description: Postgres 集群所属团队
    name: Team
    type: string
  - JSONPath: .spec.postgresql.version
    description: PostgreSQL 版本，支持 9.5 9.6 10 11 12 
    name: Version
    type: string
  - JSONPath: .spec.numberOfInstances
    description: Postgres 集群实例数量
    name: Pods
    type: integer
  - JSONPath: .spec.volume.size
    description: 存储大小
    name: Volume
    type: string
  - JSONPath: .spec.resources.requests.cpu
    description: Postgres 容器 CPU 资源请求大小
    name: CPU-Request
    type: string
  - JSONPath: .spec.resources.requests.memory
    description: Postgres 容器内存资源请求大小
    name: Memory-Request
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .status.PostgresClusterStatus
    description: PostgreSQL 集群状态
    name: Status
    type: string
  group: acid.zalan.do
  names:
    kind: postgresql
    listKind: postgresqlList
    plural: postgresqls
    shortNames:
    - pg
    singular: postgresql
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          enum:
          - acid.zalan.do/v1
          type: string
        kind:
          enum:
          - postgresql
          type: string
        spec:
          properties:
            allowedSourceRanges:
              items:
                pattern: ^(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\/(\d|[1-2]\d|3[0-2])$
                type: string
              nullable: true
              type: array
            clone:
              properties:
                cluster:
                  type: string
                s3_access_key_id:
                  type: string
                s3_endpoint:
                  type: string
                s3_force_path_style:
                  type: string
                s3_secret_access_key:
                  type: string
                s3_wal_path:
                  type: string
                timestamp:
                  pattern: ^([0-9]+)-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])[Tt]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9]|60)(\.[0-9]+)?(([Zz])|([+-]([01][0-9]|2[0-3]):[0-5][0-9]))$
                  type: string
                uid:
                  format: uuid
                  type: string
              required:
              - cluster
              type: object
            databases:
              additionalProperties:
                type: string
              type: object
            dockerImage:
              type: string
            enableLogicalBackup:
              type: boolean
            enableMasterLoadBalancer:
              type: boolean
            enableReplicaLoadBalancer:
              type: boolean
            enableShmVolume:
              type: boolean
            initContainers:
              items:
                additionalProperties: true
                type: object
              nullable: true
              type: array
            init_containers:
              items:
                additionalProperties: true
                type: object
              nullable: true
              type: array
            logicalBackupSchedule:
              pattern: ^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$
              type: string
            maintenanceWindows:
              items:
                pattern: ^\ *((Mon|Tue|Wed|Thu|Fri|Sat|Sun):(2[0-3]|[01]?\d):([0-5]?\d)|(2[0-3]|[01]?\d):([0-5]?\d))-((Mon|Tue|Wed|Thu|Fri|Sat|Sun):(2[0-3]|[01]?\d):([0-5]?\d)|(2[0-3]|[01]?\d):([0-5]?\d))\
                  *$
                type: string
              type: array
            numberOfInstances:
              minimum: 0
              type: integer
              description: 实例数量
            patroni:
              properties:
                initdb:
                  additionalProperties:
                    type: string
                  type: object
                loop_wait:
                  type: integer
                maximum_lag_on_failover:
                  type: integer
                pg_hba:
                  items:
                    type: string
                  type: array
                retry_timeout:
                  type: integer
                slots:
                  additionalProperties:
                    additionalProperties:
                      type: string
                    type: object
                  type: object
                ttl:
                  type: integer
              type: object
            podAnnotations:
              additionalProperties:
                type: string
              type: object
            podPriorityClassName:
              type: string
            enableExporter:
              type: boolean
            pod_priority_class_name:
              type: string
            postgresql:
              properties:
                parameters:
                  additionalProperties:
                    type: string
                  type: object
                version:
                  enum:
                  - '9.3'
                  - '9.4'
                  - '9.5'
                  - '9.6'
                  - '10'
                  - '11'
                  - '12'
                  type: string
              required:
              - version
              type: object
              description: PostgreSQL 数据库设置
            replicaLoadBalancer:
              type: boolean
            resources:
              properties:
                limits:
                  properties:
                    cpu:
                      pattern: ^(\d+m|\d+(\.\d{1,3})?)$
                      type: string
                    memory:
                      pattern: ^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$
                      type: string
                  required:
                  - cpu
                  - memory
                  type: object
                requests:
                  properties:
                    cpu:
                      pattern: ^(\d+m|\d+(\.\d{1,3})?)$
                      type: string
                    memory:
                      pattern: ^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$
                      type: string
                  required:
                  - cpu
                  - memory
                  type: object
              required:
              - requests
              - limits
              type: object
            sidecars:
              items:
                additionalProperties: true
                type: object
              nullable: true
              type: array
            spiloFSGroup:
              type: integer
            standby:
              properties:
                s3_wal_path:
                  type: string
              required:
              - s3_wal_path
              type: object
            teamId:
              type: string
              description: 'Postgre 集群所属团队，仅作标识用'
            tolerations:
              items:
                properties:
                  effect:
                    enum:
                    - NoExecute
                    - NoSchedule
                    - PreferNoSchedule
                    type: string
                  key:
                    type: string
                  operator:
                    enum:
                    - Equal
                    - Exists
                    type: string
                  tolerationSeconds:
                    type: integer
                  value:
                    type: string
                required:
                - key
                - operator
                - effect
                type: object
              type: array
            useLoadBalancer:
              type: boolean
            users:
              additionalProperties:
                description: Role flags specified here must not contradict each other
                items:
                  enum:
                  - bypassrls
                  - BYPASSRLS
                  - nobypassrls
                  - NOBYPASSRLS
                  - createdb
                  - CREATEDB
                  - nocreatedb
                  - NOCREATEDB
                  - createrole
                  - CREATEROLE
                  - nocreaterole
                  - NOCREATEROLE
                  - inherit
                  - INHERIT
                  - noinherit
                  - NOINHERIT
                  - login
                  - LOGIN
                  - nologin
                  - NOLOGIN
                  - replication
                  - REPLICATION
                  - noreplication
                  - NOREPLICATION
                  - superuser
                  - SUPERUSER
                  - nosuperuser
                  - NOSUPERUSER
                  type: string
                nullable: true
                type: array
              type: object
            volume:
              properties:
                size:
                  pattern: ^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$
                  type: string
                storageClass:
                  type: string
                subPath:
                  type: string
              required:
              - size
              type: object
          required:
          - numberOfInstances
          - teamId
          - postgresql
          type: object
      required:
      - kind
      - apiVersion
      - spec
      type: object
  version: v1

