apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels: {app: strimzi, strimzi.io/crd-install: 'true'}
  name: kafkaconnectors.kafka.strimzi.io
spec:
  group: kafka.strimzi.io
  names:
    categories: [strimzi]
    kind: KafkaConnector
    listKind: KafkaConnectorList
    plural: kafkaconnectors
    shortNames: [kctr]
    singular: kafkaconnector
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: 配置kafka connector的规范
          properties:
            class: {description: 用于Kafka连接器的类, type: string}
            config: {description: 'Kafka连接器配置 无法设置以下属性:connector.class, tasks.max', type: object}
            pause: {description: 连接器是否应该暂停 默认值为false, type: boolean}
            tasksMax: {description: 最大任务数1, minimum: 1, type: integer}
          type: object
        status:
          description: kafka连接器状态
          properties:
            conditions:
              description: 状态列表
              items:
                properties:
                  lastTransitionTime: {description: '上次资源类型状态，要求的格式为yyyy-MM-ddTHH:mm:ssZ UTC时区', type: string}
                  message: {description: 上次资源类型变更的详情., type: string}
                  reason: {description: 最后一次状态改变的原因., type: string}
                  status: {description: '状态或者是true，或者是false，或者是未知', type: string}
                  type: {description: '条件唯一标识符', type: string}
                type: object
              type: array
            connectorStatus: {description: '连接器状态', type: object}
            observedGeneration: {description: 操作符最后调解的CRD的生成, type: integer}
          type: object
  version: v1alpha1
  versions:
  - {name: v1alpha1, served: true, storage: true}

